name: CI

on:
  push:
    branches:
      - main  # Adjust branch name if necessary
  pull_request:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Adjust Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if you have specific requirements

      - name: Run tests with Selenium
        run: |
          python manage.py test
